
HTTPS_PROXY= http://193.51.24.15:3128
export HTTP_PROXY

all:
	@wget -qi URL
	@mv known_exploited_vulnerabilities.json old/
	@mv known_exploited_vulnerabilities.json.1 known_exploited_vulnerabilities.json
